---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-backup
rules:
- apiGroups:
  - ""
  - v1
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-backup
subjects:
- kind: ServiceAccount
  name: kubernetes-backup
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-backup
  namespace: {{ .Release.Namespace }}